spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show-sql: false
        format_sql: false
  jackson:
    default-property-inclusion: NON_NULL
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true
    locations:classpath: db/migration
    table: flyway_schema_history
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: fala_user
    password: 'falapassword'
    driverClassName: org.postgresql.Driver
    initialization-mode: ALWAYS
    continue-on-error: false

server:
  error:
    include-binding-errors: always
    include-message: always