CREATE TABLE IF NOT EXISTS product (
  id BIGSERIAL PRIMARY KEY,
  sku VARCHAR(13) NOT NULL,
  name VARCHAR(50) NOT NULL,
  brand VARCHAR(50) NOT NULL,
  size VARCHAR(50) DEFAULT '-',
  price NUMERIC NOT NULL DEFAULT 0.00,
  principal_image VARCHAR(250) NOT NULL
);


